### DISCUSSION TITLE
pl-topologicalcopy in pipelines

### DISCUSSION THREAD

**Discussion by jennydaman** [FNNDSC/ChRIS_ultron_backEnd#481] [Ideas]
## Abstract

Several limitations to the current support for "feed join" operations, implemented by `pl-topologicalcopy`, make it impossible for "feed join" to be used in pipelines. To support "feed join" operations in pipelines, here a solution is proposed: (A) _ts_ plugins should be able to wait on multiple parents, (B) _ts_-plugins should be supported in pipelines by using Piping.id for values of the parameter `plugininstances`.

## Definitions

**Feed join**: creating a plugin instance in a feed where its inputs are the files of two or more plugin instances in the same feed.

## Background

"Topology synthesis" or _ts_-type plugins were conceived to be a type of _ChRIS_ plugin which interacts with its own feed in special ways: in contrast to _ds_-type plugins, the inputs of a _ts_-plugin include more than just the files of its "previous"/parent plugin instance. Currently, _ts_-plugins are implemented as a special case in the backend:

https://github.com/FNNDSC/ChRIS_ultron_backEnd/blob/5d3c2e288528571677feb3fbc110d668de5ad164/chris_backend/plugininstances/services/manager.py#L281-L329

_ts_ plugins can be described more specifically by explaining the code: a _ts_ plugin is a _ds_ plugin which is assumed to have the parameters `plugininstances`, `filter`, and `groupByInstance`. Before a _ts_ plugin runs, CUBE executes some special code to collect the files from every plugin instance specified by `plugininstances`. These files are used as the input to the _ts_-plugin instance.

The _ts_-plugin [pl-topologicalcopy](https://github.com/FNNDSC/pl-topologicalcopy) is used to perform "join" operations.

In the current implementation there is a problem where _ts_ plugin instances have a **data dependency** on the plugin instances specified by their `plugininstances` parameter, howeThis topic was discussed during the _ChRIS_ roundtable on 2023-01-10ver this data dependency is not satisfied because it is possible for a _ts_-plugin to start running before its dependencies are in the state `finishedSuccessfully`. Due to this issue, _ts_-plugins cannot be used in pipelines.

A second issue is that the value for the parameter `plugininstances` can only be figured out at runtime, which makes it impossible to specify its value in a pipeline.

## Proposal

To support _feed join_ operations in pipelines, _ts_ plugins should be able to wait on multiple parents, and pipelines should be allowed to specify a value for the parameter `plugininstances` by list index.

### Wait on multiple parents

Simple as that. _ts_-plugins are currently implemented as "special cases" in manager.py, so why not implement them as a special case in tasks.py as well?

https://github.com/FNNDSC/ChRIS_ultron_backEnd/blob/5d3c2e288528571677feb3fbc110d668de5ad164/chris_backend/plugininstances/tasks.py#L72-L84

Counterarguments: algorithmic complexity, poor scalability: we don't care about scalability right now. A reasonable _ChRIS_ deployment might look like <20,000 plugin instances, CUBE running on a single machine with 16GB RAM.

### `plugininstances` parameter in pipelines

1. The `plugininstances` parameter in a pipeline should accept a CSV of list indices, just as what is accepted by the `previous_index` argument.
2. When serializing a _ts_-type piping, the value for `plugininstances` should be mapped from list indices to Piping.id.
3. During workflow creation, plugin instances should be created breadth-first
4. During creation of a plugin instance of a _ts_-type piping, the value for `plugininstances` should be mapped from Piping.id to PluginInstance.id

##### 1. Canonical JSON representation of example pipeline

```json
"plugin_tree": [
  {
    "title": "Convert NIFTI to MINC",
    "plugin_name": "pl-nii2mnc-u8",
    "plugin_version": "1.0.1",
    "previous_index": null
  },
  {
    "title": "Left WM mask",
    "plugin_name": "pl-nums2mask",
    "plugin_version": "1.0.1",
    "previous_index": 0,
    "plugin_parameter_defaults": [
      {
        "name": "value",
        "default": 160
      }
    ]
  },
  {
    "title": "Right WM mask",
    "plugin_name": "pl-nums2mask",
    "plugin_version": "1.0.1",
    "previous_index": 0,
    "plugin_parameter_defaults": [
      {
        "name": "value",
        "default": 161
      }
    ]
  },
  {
    "title": "Join Left and Right masks into same directory",
    "plugin_name": "pl-topologicalcopy",
    "plugin_version": "0.3",
    "previous_index": 2,
    "plugin_parameter_defaults": [
      {
        "name": "plugininstances",
        "default": "1,2"
      }
    ]
  },
  {
    "title": "Surface extraction",
    "plugin_name": "pl-fetal-cp-surface-extract",
    "plugin_version": "1.1.0",
    "previous_index": 3
  }
]
```

###### ASCII art diagram of example pipeline

```
    O      0: pl-nii2mnc-u8
   / \
  /   \
 |     O   1: pl-nums2mask --value 160
 O     |   2: pl-nums2mask --value 161
  \   /
   \ /
    O      3: pl-topologicalcopy --plugininstances 1,2
    |
    |
    O      4: pl-fetal-cp-surface-extract

```

##### 1.1. As a [RFC \#2 YAML file](https://github.com/FNNDSC/CHRIS_docs/blob/7ad87ff25b6b1d4e88b408a4f8c47fd347b49452/specs/YAML_Pipelines.adoc)

Also proposed is for piping title to be used in the value for `plugininstances` instead of list indices.

```yaml
name: "Example pipeline containing ts piping"
authors: "Jennings Zhang <Jennings.Zhang@childrens.harvard.edu>"
category: "Example"
description: "Input is a T1 nuc NIFTI"
locked: false
plugin_tree:

  # pipeline root node
- title: "Convert NIFTI to MINC"
  plugin: pl-nii2mnc-u8 v1.0.1
  previous: null

  # two sibling children of root
- title: "Left WM mask"
  plugin: pl-nums2mask v1.0.1
  previous: "Convert NIFTI to MINC"
  plugin_parameter_defaults:
    value: 160
- title: "Right WM mask"
  plugin: pl-nums2mask v1.0.1
  previous: "Convert NIFTI to MINC"
  plugin_parameter_defaults:
    value: 161

  # feed join operation on siblings
- title: "Join Left and Right masks into same directory"
  plugin: pl-topologicalcopy v0.3
  previous: "Right WM mask"
  plugin_parameter_defaults:
    plugininstances: 'Left WM Mask,Right WM Mask'

  # process joined files
- title: "Surface extraction"
  plugin: pl-fetal-cp-surface-extract v1.1.0
  previous: "Join Left and Right masks into same directory"
```

#### 2. Mapping list indices -> Piping.id

For example, CUBE assigns the following piping IDs:

| id | title |
|----|------|
| 76 | Convert NIFTI to MINC |
| 77 | Left WM mask |
| 78 | Right WM mask |
| 79 | Join Left and Right masks into same directory |
| 80 | Surface extraction |

The plugin parameter defaults for piping 79 will be:

```json
{
  "url": "https://example.com/api/v1/pipelines/string-parameter/2555/",
  "id": 2555,
  "value": "77,78",
  "type": "string",
  "plugin_piping_id": 79,
  "plugin_piping_title": "Join Left and Right masks into same directory",
  "previous_plugin_piping_id": 78,
  "param_name": "plugininstances",
  "param_id": 571,
  "plugin_piping": "https://example.com/api/v1/pipelines/pipings/79/",
  "plugin_name": "pl-topologicalcopy",
  "plugin_version": "0.3",
  "plugin_id": 102,
  "plugin_param": "https://example.com/api/v1/plugins/parameters/571/"
}
```

#### 3-4 Breadth-first creation of plugin instances

First, user requests workflow to be created.
CUBE creates plugin instances from pipings breadth-first:

|piping | plugininstance | 
|----------|----------|
| 76 | 111|
| 77 | 112 |
|78 | 113 |

Piping 79 is a _ts_-type piping, which is handled as a special case. Its parameter `plugininstances` is mapped from piping IDs to plugin instance IDs: the pipeline string parameter value `77,78` gets transformed to a plugin instance parameter value `112,113`.

Final result:

|piping | plugininstance | 
|----------|----------|
| 76 | 111|
| 77 | 112 |
| 78 | 113 |
| 79 | 114 |
| 80 | 115 |

###### ASCII art diagram of created workflow

```
    O      111: pl-nii2mnc-u8
   / \
  /   \
 |     O   112: pl-nums2mask --value 160
 O     |   113: pl-nums2mask --value 161
  \   /
   \ /
    O      114: pl-topologicalcopy --plugininstances 112,113
    |
    |
    O      115: pl-fetal-cp-surface-extract
```

#### Summary of Value Mapping

| title | list index | piping | plugin instance |
|-------|---------------|-----------|------------------------|
| Convert NIFTI to MINC | 0 | 76 | 111 |
| Left WM mask | 1 | 77 | 112 | 
| Right WM mask | 2 | 78 | 113 |
| Join Left and Right masks into same directory | 3 | 79 | 114 |
| Surface extraction | 4 | 80 | 115 |

#### Transformation of parameter value for `plugininstances`

1. As a YAML pipeline: `"Rename left mask files,Rename right mask files"`
1. As a JSON pipeline: `"1,2"`
2. As a pipeline in CUBE: `"77,78"`
3. As a workflow: `"112,113"`

### Alternative Solutions

Dynamic plugins: see #482 tl;dr since a reasonableimplementation for dynamic plugins would require new features in CUBE anyways, better we just add this proposal instead.

Multiple parents: see #483 tl;dr all plugins may have [0, n) parents, a plugin with >1 parent will automatically do a feed join. This solution would be too much work.

### Summary and Considerations:

- API is backwards-compatible
- upholds and extends the current idea of _ts_-type plugins
- new behavior where pl-topologicalcopy waits on its dependencies
- new behavior allowing pl-topologicalcopy to be used in pipelines
- CUBE performance and scalability worsened

### Meeting Attendance

This topic was discussed during the _ChRIS_ roundtable on 2023-01-10

In attendance: Rudolph, Jennings, Gideon, Sandip

Jorge was absent.
