### ISSUE TITLE
pman / pfioh update broke integration tests

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/ChRIS_ultron_backEnd#104]
Early April PR on pman / pfioh broke integration testing.

**Comment by rudolphpienaar** [comment]
Fresh checkout of all relevant components:
* CUBE
* pfioh
* pfcon
* pman
* pfurl

**Comment by rudolphpienaar** [comment]
Map dirs from source into containers...

```
    volumes:
      - ../pfcon/pfcon/pfcon.py:/usr/local/lib/python3.5/dist-packages/pfcon/pfcon.py

    volumes:
      - ./FS/remote:/hostFS/storeBase
      - ../pfioh/pfioh/pfioh.py:/usr/lib/python3.5/site-packages/pfioh/pfioh.py

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./FS/remote:/hostFS/storeBase
      - ../pman/pman/pman.py:/usr/local/lib/python3.5/dist-packages/pman/pman.py
```
