### ISSUE TITLE
Able to see parameters of plugin instances from other users feeds

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ultron_backEnd#500]
Users are able to see the plugin instance parameters of other users, even in situations where (a) current user is not owner of plugin instance, (b) feed of plugin instance is not shared with current user, (c) current user's username is not `chris`

I found this issue via this setup:

1. Create two users (usernames should not be `chris`). e.g. with `chrisomatic.yml`:

```yaml

cube:
  users:
  - username: bobb
    password: bobb1234
  - username: alice
    password: alice1234
```

2. Run `pl-dircopy` with one user, e.g. `chrs upload --username bobb --password bobb1234 --address http://localhost:8000/api/v1/ --feed "bobbs feed" README.md`
3. As the other user (alice), log into ChRIS_ui and try running `pl-dircopy`: "New and Existing Analyses" > "Create New Analysis" > "Generate Data" > "pl-dircopy" > "Fill the form using a latest run of this plugin

As the `alice` user, I will see `bobb`'s plugin instance parameters filled in.
